### ISSUE TITLE
为何动态获取的评分跟组件的星号对应不上？

### ISSUE THREAD

**Issue by wkjjkw** [simsir-lin/multiple-rate-wxapp#2]
页面是这样的：
```
    <view class='item'>
      <text>质量：</text>
      <multiple-rate rate="{{qualityRate}}" disabled="true">
      <text style='margin-left:20px;'>{{ qualityRate }}分</text>
      </multiple-rate>
    </view>
    <view class='item'>
      <text>速度：</text>
      <multiple-rate rate="{{speedRate}}" disabled="true">
      <text style='margin-left:20px;'>{{ speedRate }}分</text>
      </multiple-rate>
    </view>
    <view class='item'>
      <text>态度：</text>
      <multiple-rate rate="{{attitudeRate}}" disabled="true">
      <text style='margin-left:20px;'>{{ attitudeRate }}分</text>
      </multiple-rate>
    </view>
```
逻辑是这样的：
```
    that.setData({
            orderDetail: res.data.data,
            qualityRate: res.data.data.evastar.split(',')[0],
            speedRate: res.data.data.evastar.split(',')[1],
            attitudeRate: res.data.data.evastar.split(',')[2]
          })
```
数字是获取到了，但是对应的星号却是错误的：
![TIM截图20190506095548](https://user-images.githubusercontent.com/26787245/57203735-27f3e500-6fe5-11e9-8553-f13b534e2676.png)

**Comment by ZhengMengSi** [comment]
我也遇到这个问题了，你是怎么解决的？

**Comment by simsir-lin** [comment]
请尝试新的版本😊

**Comment by ZhengMengSi** [comment]
感谢



------------------ 原始邮件 ------------------
发件人: "林浩裕"<notifications@github.com>; 
发送时间: 2019年9月10日(星期二) 下午3:46
收件人: "simsir-lin/wechat-miniprogram-rate"<wechat-miniprogram-rate@noreply.github.com>; 
抄送: "张梦思"<547151644@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [simsir-lin/wechat-miniprogram-rate] 为何动态获取的评分跟组件的星号对应不上？ (#2)




请尝试新的版本😊
 
&mdash;

**Comment by callmesoul** [comment]
我自己写了个高可定制的
https://github.com/callmesoul/wechat-miniprogram-rate-plugin
